export * from "./AuthPage";
export * from "./MainPage";
export * from "./CatalogPage";
export * from "./ProductPage";
export * from "./OrderPage";
export * from "./LkPage";
export * from "./CartBlock";
export * from "./ProfileBlock";
export * from "./WishlistBlock";
